"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AddressSpace:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AddressSpaceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AddressSpace.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FxPakPro: _AddressSpace.ValueType  # 0
    """The default is the FX Pak Pro / SD2SNES's address space:
    $00_0000..$DF_FFFF =   ROM contents, linearly mapped
    $E0_0000..$EF_FFFF =  SRAM contents, linearly mapped
    $F5_0000..$F6_FFFF =  WRAM contents, linearly mapped
    $F7_0000..$F7_FFFF =  VRAM contents, linearly mapped
    $F8_0000..$F8_FFFF =   APU contents, linearly mapped
    $F9_0000..$F9_01FF = CGRAM contents, linearly mapped
    $F9_0200..$F9_041F =   OAM contents, linearly mapped
    $F9_0420..$F9_04FF =  MISC contents, linearly mapped
    $F9_0500..$F9_06FF =         PPUREG, linearly mapped
    $F9_0700..$F9_08FF =         CPUREG, linearly mapped
    translated device address depends on device being talked to and its current MemoryMapping mode
    SNES
    """
    SnesABus: _AddressSpace.ValueType  # 1
    """The SNES's main A-bus; address depends on device's current MemoryMapping mode, e.g. LoROM, HiROM, ExHiROM, etc."""
    Raw: _AddressSpace.ValueType  # 2
    """Do not do any address translation; simply pass the raw address to the device as-is:"""

class AddressSpace(_AddressSpace, metaclass=_AddressSpaceEnumTypeWrapper):
    """////////////////////////////////////////////////////////////////////////////////////////////////
    enums
    ////////////////////////////////////////////////////////////////////////////////////////////////

    address space used to interpret an address in:
    """

FxPakPro: AddressSpace.ValueType  # 0
"""The default is the FX Pak Pro / SD2SNES's address space:
$00_0000..$DF_FFFF =   ROM contents, linearly mapped
$E0_0000..$EF_FFFF =  SRAM contents, linearly mapped
$F5_0000..$F6_FFFF =  WRAM contents, linearly mapped
$F7_0000..$F7_FFFF =  VRAM contents, linearly mapped
$F8_0000..$F8_FFFF =   APU contents, linearly mapped
$F9_0000..$F9_01FF = CGRAM contents, linearly mapped
$F9_0200..$F9_041F =   OAM contents, linearly mapped
$F9_0420..$F9_04FF =  MISC contents, linearly mapped
$F9_0500..$F9_06FF =         PPUREG, linearly mapped
$F9_0700..$F9_08FF =         CPUREG, linearly mapped
translated device address depends on device being talked to and its current MemoryMapping mode
SNES
"""
SnesABus: AddressSpace.ValueType  # 1
"""The SNES's main A-bus; address depends on device's current MemoryMapping mode, e.g. LoROM, HiROM, ExHiROM, etc."""
Raw: AddressSpace.ValueType  # 2
"""Do not do any address translation; simply pass the raw address to the device as-is:"""
global___AddressSpace = AddressSpace

class _MemoryMapping:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MemoryMappingEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MemoryMapping.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Unknown: _MemoryMapping.ValueType  # 0
    HiROM: _MemoryMapping.ValueType  # 1
    LoROM: _MemoryMapping.ValueType  # 2
    ExHiROM: _MemoryMapping.ValueType  # 3
    """(48-64Mbit)"""

class MemoryMapping(_MemoryMapping, metaclass=_MemoryMappingEnumTypeWrapper):
    """memory mapping mode of a SNES cart:"""

Unknown: MemoryMapping.ValueType  # 0
HiROM: MemoryMapping.ValueType  # 1
LoROM: MemoryMapping.ValueType  # 2
ExHiROM: MemoryMapping.ValueType  # 3
"""(48-64Mbit)"""
global___MemoryMapping = MemoryMapping

class _DeviceCapability:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DeviceCapabilityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DeviceCapability.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ReadMemory: _DeviceCapability.ValueType  # 1
    WriteMemory: _DeviceCapability.ValueType  # 2
    ExecuteASM: _DeviceCapability.ValueType  # 3
    ResetSystem: _DeviceCapability.ValueType  # 4
    PauseUnpauseEmulation: _DeviceCapability.ValueType  # 5
    PauseToggleEmulation: _DeviceCapability.ValueType  # 6
    ResetToMenu: _DeviceCapability.ValueType  # 7
    FetchFields: _DeviceCapability.ValueType  # 8
    ReadDirectory: _DeviceCapability.ValueType  # 10
    MakeDirectory: _DeviceCapability.ValueType  # 11
    RemoveFile: _DeviceCapability.ValueType  # 12
    RenameFile: _DeviceCapability.ValueType  # 13
    PutFile: _DeviceCapability.ValueType  # 14
    GetFile: _DeviceCapability.ValueType  # 15
    BootFile: _DeviceCapability.ValueType  # 16
    NWACommand: _DeviceCapability.ValueType  # 20

class DeviceCapability(_DeviceCapability, metaclass=_DeviceCapabilityEnumTypeWrapper):
    """capabilities of a device"""

ReadMemory: DeviceCapability.ValueType  # 1
WriteMemory: DeviceCapability.ValueType  # 2
ExecuteASM: DeviceCapability.ValueType  # 3
ResetSystem: DeviceCapability.ValueType  # 4
PauseUnpauseEmulation: DeviceCapability.ValueType  # 5
PauseToggleEmulation: DeviceCapability.ValueType  # 6
ResetToMenu: DeviceCapability.ValueType  # 7
FetchFields: DeviceCapability.ValueType  # 8
ReadDirectory: DeviceCapability.ValueType  # 10
MakeDirectory: DeviceCapability.ValueType  # 11
RemoveFile: DeviceCapability.ValueType  # 12
RenameFile: DeviceCapability.ValueType  # 13
PutFile: DeviceCapability.ValueType  # 14
GetFile: DeviceCapability.ValueType  # 15
BootFile: DeviceCapability.ValueType  # 16
NWACommand: DeviceCapability.ValueType  # 20
global___DeviceCapability = DeviceCapability

class _Field:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FieldEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Field.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DeviceName: _Field.ValueType  # 0
    DeviceVersion: _Field.ValueType  # 1
    DeviceStatus: _Field.ValueType  # 2
    CoreName: _Field.ValueType  # 20
    CoreVersion: _Field.ValueType  # 21
    CorePlatform: _Field.ValueType  # 22
    RomFileName: _Field.ValueType  # 40
    RomHashType: _Field.ValueType  # 41
    RomHashValue: _Field.ValueType  # 42

class Field(_Field, metaclass=_FieldEnumTypeWrapper):
    """fields to query from DeviceInfo.FetchFields"""

DeviceName: Field.ValueType  # 0
DeviceVersion: Field.ValueType  # 1
DeviceStatus: Field.ValueType  # 2
CoreName: Field.ValueType  # 20
CoreVersion: Field.ValueType  # 21
CorePlatform: Field.ValueType  # 22
RomFileName: Field.ValueType  # 40
RomHashType: Field.ValueType  # 41
RomHashValue: Field.ValueType  # 42
global___Field = Field

class _DirEntryType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DirEntryTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DirEntryType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Directory: _DirEntryType.ValueType  # 0
    File: _DirEntryType.ValueType  # 1

class DirEntryType(_DirEntryType, metaclass=_DirEntryTypeEnumTypeWrapper): ...

Directory: DirEntryType.ValueType  # 0
File: DirEntryType.ValueType  # 1
global___DirEntryType = DirEntryType

@typing_extensions.final
class DevicesRequest(google.protobuf.message.Message):
    """////////////////////////////////////////////////////////////////////////////////////////////////
    devices messages
    ////////////////////////////////////////////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KINDS_FIELD_NUMBER: builtins.int
    @property
    def kinds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """optional list of device kind filters
        TODO: repeated DeviceCapability capabilities;
        """
    def __init__(
        self,
        *,
        kinds: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["kinds", b"kinds"]) -> None: ...

global___DevicesRequest = DevicesRequest

@typing_extensions.final
class DevicesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Device(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        URI_FIELD_NUMBER: builtins.int
        DISPLAYNAME_FIELD_NUMBER: builtins.int
        KIND_FIELD_NUMBER: builtins.int
        CAPABILITIES_FIELD_NUMBER: builtins.int
        DEFAULTADDRESSSPACE_FIELD_NUMBER: builtins.int
        SYSTEM_FIELD_NUMBER: builtins.int
        uri: builtins.str
        """URI that describes exactly how to connect to the device, e.g.:
        RetroArch:  "ra://127.0.0.1:55355"
        FX Pak Pro: "fxpakpro://./dev/cu.usbmodemDEMO000000001" (MacOS)
                    "fxpakpro://./COM4"                         (Windows)
                    "fxpakpro://./dev/ttyACM0"                  (Linux)
        uri is used as the unique identifier of the device for clients to refer to
        """
        displayName: builtins.str
        """friendly display name of the device"""
        kind: builtins.str
        """device kind, e.g. "fxpakpro", "retroarch", "lua" """
        @property
        def capabilities(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___DeviceCapability.ValueType]:
            """all device capabilities:"""
        defaultAddressSpace: global___AddressSpace.ValueType
        """default address space for the device:"""
        system: builtins.str
        """[DEPRECATED] console system supported, e.g. "snes", "n64"
        since devices can support multiple systems, it's better to fetch platform from DeviceInfo.FetchFields method
        """
        def __init__(
            self,
            *,
            uri: builtins.str = ...,
            displayName: builtins.str = ...,
            kind: builtins.str = ...,
            capabilities: collections.abc.Iterable[global___DeviceCapability.ValueType] | None = ...,
            defaultAddressSpace: global___AddressSpace.ValueType = ...,
            system: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["capabilities", b"capabilities", "defaultAddressSpace", b"defaultAddressSpace", "displayName", b"displayName", "kind", b"kind", "system", b"system", "uri", b"uri"]) -> None: ...

    DEVICES_FIELD_NUMBER: builtins.int
    @property
    def devices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DevicesResponse.Device]: ...
    def __init__(
        self,
        *,
        devices: collections.abc.Iterable[global___DevicesResponse.Device] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["devices", b"devices"]) -> None: ...

global___DevicesResponse = DevicesResponse

@typing_extensions.final
class ResetSystemRequest(google.protobuf.message.Message):
    """////////////////////////////////////////////////////////////////////////////////////////////////
    control messages
    ////////////////////////////////////////////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    uri: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uri", b"uri"]) -> None: ...

global___ResetSystemRequest = ResetSystemRequest

@typing_extensions.final
class ResetSystemResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    uri: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uri", b"uri"]) -> None: ...

global___ResetSystemResponse = ResetSystemResponse

@typing_extensions.final
class ResetToMenuRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    uri: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uri", b"uri"]) -> None: ...

global___ResetToMenuRequest = ResetToMenuRequest

@typing_extensions.final
class ResetToMenuResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    uri: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uri", b"uri"]) -> None: ...

global___ResetToMenuResponse = ResetToMenuResponse

@typing_extensions.final
class PauseEmulationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PAUSED_FIELD_NUMBER: builtins.int
    uri: builtins.str
    paused: builtins.bool
    """true to pause emulation, false to unpause"""
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        paused: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["paused", b"paused", "uri", b"uri"]) -> None: ...

global___PauseEmulationRequest = PauseEmulationRequest

@typing_extensions.final
class PauseEmulationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PAUSED_FIELD_NUMBER: builtins.int
    uri: builtins.str
    paused: builtins.bool
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        paused: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["paused", b"paused", "uri", b"uri"]) -> None: ...

global___PauseEmulationResponse = PauseEmulationResponse

@typing_extensions.final
class PauseToggleEmulationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    uri: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uri", b"uri"]) -> None: ...

global___PauseToggleEmulationRequest = PauseToggleEmulationRequest

@typing_extensions.final
class PauseToggleEmulationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    uri: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uri", b"uri"]) -> None: ...

global___PauseToggleEmulationResponse = PauseToggleEmulationResponse

@typing_extensions.final
class DetectMemoryMappingRequest(google.protobuf.message.Message):
    """////////////////////////////////////////////////////////////////////////////////////////////////
    memory messages
    ////////////////////////////////////////////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    FALLBACKMEMORYMAPPING_FIELD_NUMBER: builtins.int
    ROMHEADER00FFB0_FIELD_NUMBER: builtins.int
    uri: builtins.str
    fallbackMemoryMapping: global___MemoryMapping.ValueType
    """optional fallback value to set in case detection fails for some reason"""
    romHeader00FFB0: builtins.bytes
    """optional ROM header (from bus address $00:FFB0, at least $30 bytes long) to use for detection
    if not provided, the header will be read from the device
    """
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        fallbackMemoryMapping: global___MemoryMapping.ValueType | None = ...,
        romHeader00FFB0: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_fallbackMemoryMapping", b"_fallbackMemoryMapping", "_romHeader00FFB0", b"_romHeader00FFB0", "fallbackMemoryMapping", b"fallbackMemoryMapping", "romHeader00FFB0", b"romHeader00FFB0"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_fallbackMemoryMapping", b"_fallbackMemoryMapping", "_romHeader00FFB0", b"_romHeader00FFB0", "fallbackMemoryMapping", b"fallbackMemoryMapping", "romHeader00FFB0", b"romHeader00FFB0", "uri", b"uri"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fallbackMemoryMapping", b"_fallbackMemoryMapping"]) -> typing_extensions.Literal["fallbackMemoryMapping"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_romHeader00FFB0", b"_romHeader00FFB0"]) -> typing_extensions.Literal["romHeader00FFB0"] | None: ...

global___DetectMemoryMappingRequest = DetectMemoryMappingRequest

@typing_extensions.final
class DetectMemoryMappingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    MEMORYMAPPING_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    ROMHEADER00FFB0_FIELD_NUMBER: builtins.int
    uri: builtins.str
    memoryMapping: global___MemoryMapping.ValueType
    """the memory mapping mode detected"""
    confidence: builtins.bool
    """true if confident we detected a mapping; false if using a fallback or default value"""
    romHeader00FFB0: builtins.bytes
    """the ROM header read from $00:FFB0, length is $50 bytes if server reads it, otherwise length of `romHeader00FFB0` from request"""
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        memoryMapping: global___MemoryMapping.ValueType = ...,
        confidence: builtins.bool = ...,
        romHeader00FFB0: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["confidence", b"confidence", "memoryMapping", b"memoryMapping", "romHeader00FFB0", b"romHeader00FFB0", "uri", b"uri"]) -> None: ...

global___DetectMemoryMappingResponse = DetectMemoryMappingResponse

@typing_extensions.final
class ReadMemoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUESTADDRESS_FIELD_NUMBER: builtins.int
    REQUESTADDRESSSPACE_FIELD_NUMBER: builtins.int
    REQUESTMEMORYMAPPING_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    requestAddress: builtins.int
    requestAddressSpace: global___AddressSpace.ValueType
    requestMemoryMapping: global___MemoryMapping.ValueType
    size: builtins.int
    def __init__(
        self,
        *,
        requestAddress: builtins.int = ...,
        requestAddressSpace: global___AddressSpace.ValueType = ...,
        requestMemoryMapping: global___MemoryMapping.ValueType = ...,
        size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["requestAddress", b"requestAddress", "requestAddressSpace", b"requestAddressSpace", "requestMemoryMapping", b"requestMemoryMapping", "size", b"size"]) -> None: ...

global___ReadMemoryRequest = ReadMemoryRequest

@typing_extensions.final
class ReadMemoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUESTADDRESS_FIELD_NUMBER: builtins.int
    REQUESTADDRESSSPACE_FIELD_NUMBER: builtins.int
    REQUESTMEMORYMAPPING_FIELD_NUMBER: builtins.int
    DEVICEADDRESS_FIELD_NUMBER: builtins.int
    DEVICEADDRESSSPACE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    requestAddress: builtins.int
    requestAddressSpace: global___AddressSpace.ValueType
    requestMemoryMapping: global___MemoryMapping.ValueType
    deviceAddress: builtins.int
    """the address sent to the device and its space"""
    deviceAddressSpace: global___AddressSpace.ValueType
    data: builtins.bytes
    def __init__(
        self,
        *,
        requestAddress: builtins.int = ...,
        requestAddressSpace: global___AddressSpace.ValueType = ...,
        requestMemoryMapping: global___MemoryMapping.ValueType = ...,
        deviceAddress: builtins.int = ...,
        deviceAddressSpace: global___AddressSpace.ValueType = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "deviceAddress", b"deviceAddress", "deviceAddressSpace", b"deviceAddressSpace", "requestAddress", b"requestAddress", "requestAddressSpace", b"requestAddressSpace", "requestMemoryMapping", b"requestMemoryMapping"]) -> None: ...

global___ReadMemoryResponse = ReadMemoryResponse

@typing_extensions.final
class WriteMemoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUESTADDRESS_FIELD_NUMBER: builtins.int
    REQUESTADDRESSSPACE_FIELD_NUMBER: builtins.int
    REQUESTMEMORYMAPPING_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    requestAddress: builtins.int
    requestAddressSpace: global___AddressSpace.ValueType
    requestMemoryMapping: global___MemoryMapping.ValueType
    data: builtins.bytes
    def __init__(
        self,
        *,
        requestAddress: builtins.int = ...,
        requestAddressSpace: global___AddressSpace.ValueType = ...,
        requestMemoryMapping: global___MemoryMapping.ValueType = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "requestAddress", b"requestAddress", "requestAddressSpace", b"requestAddressSpace", "requestMemoryMapping", b"requestMemoryMapping"]) -> None: ...

global___WriteMemoryRequest = WriteMemoryRequest

@typing_extensions.final
class WriteMemoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUESTADDRESS_FIELD_NUMBER: builtins.int
    REQUESTADDRESSSPACE_FIELD_NUMBER: builtins.int
    REQUESTMEMORYMAPPING_FIELD_NUMBER: builtins.int
    DEVICEADDRESS_FIELD_NUMBER: builtins.int
    DEVICEADDRESSSPACE_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    requestAddress: builtins.int
    requestAddressSpace: global___AddressSpace.ValueType
    requestMemoryMapping: global___MemoryMapping.ValueType
    deviceAddress: builtins.int
    deviceAddressSpace: global___AddressSpace.ValueType
    size: builtins.int
    def __init__(
        self,
        *,
        requestAddress: builtins.int = ...,
        requestAddressSpace: global___AddressSpace.ValueType = ...,
        requestMemoryMapping: global___MemoryMapping.ValueType = ...,
        deviceAddress: builtins.int = ...,
        deviceAddressSpace: global___AddressSpace.ValueType = ...,
        size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["deviceAddress", b"deviceAddress", "deviceAddressSpace", b"deviceAddressSpace", "requestAddress", b"requestAddress", "requestAddressSpace", b"requestAddressSpace", "requestMemoryMapping", b"requestMemoryMapping", "size", b"size"]) -> None: ...

global___WriteMemoryResponse = WriteMemoryResponse

@typing_extensions.final
class SingleReadMemoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def request(self) -> global___ReadMemoryRequest: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        request: global___ReadMemoryRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["request", b"request", "uri", b"uri"]) -> None: ...

global___SingleReadMemoryRequest = SingleReadMemoryRequest

@typing_extensions.final
class SingleReadMemoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def response(self) -> global___ReadMemoryResponse: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        response: global___ReadMemoryResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["response", b"response", "uri", b"uri"]) -> None: ...

global___SingleReadMemoryResponse = SingleReadMemoryResponse

@typing_extensions.final
class SingleWriteMemoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def request(self) -> global___WriteMemoryRequest: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        request: global___WriteMemoryRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["request", b"request", "uri", b"uri"]) -> None: ...

global___SingleWriteMemoryRequest = SingleWriteMemoryRequest

@typing_extensions.final
class SingleWriteMemoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def response(self) -> global___WriteMemoryResponse: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        response: global___WriteMemoryResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["response", b"response", "uri", b"uri"]) -> None: ...

global___SingleWriteMemoryResponse = SingleWriteMemoryResponse

@typing_extensions.final
class MultiReadMemoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    REQUESTS_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def requests(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ReadMemoryRequest]: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        requests: collections.abc.Iterable[global___ReadMemoryRequest] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["requests", b"requests", "uri", b"uri"]) -> None: ...

global___MultiReadMemoryRequest = MultiReadMemoryRequest

@typing_extensions.final
class MultiReadMemoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    RESPONSES_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def responses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ReadMemoryResponse]: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        responses: collections.abc.Iterable[global___ReadMemoryResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["responses", b"responses", "uri", b"uri"]) -> None: ...

global___MultiReadMemoryResponse = MultiReadMemoryResponse

@typing_extensions.final
class MultiWriteMemoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    REQUESTS_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def requests(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WriteMemoryRequest]: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        requests: collections.abc.Iterable[global___WriteMemoryRequest] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["requests", b"requests", "uri", b"uri"]) -> None: ...

global___MultiWriteMemoryRequest = MultiWriteMemoryRequest

@typing_extensions.final
class MultiWriteMemoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    RESPONSES_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def responses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WriteMemoryResponse]: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        responses: collections.abc.Iterable[global___WriteMemoryResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["responses", b"responses", "uri", b"uri"]) -> None: ...

global___MultiWriteMemoryResponse = MultiWriteMemoryResponse

@typing_extensions.final
class ReadDirectoryRequest(google.protobuf.message.Message):
    """////////////////////////////////////////////////////////////////////////////////////////////////
    filesystem messages
    ////////////////////////////////////////////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["path", b"path", "uri", b"uri"]) -> None: ...

global___ReadDirectoryRequest = ReadDirectoryRequest

@typing_extensions.final
class DirEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    type: global___DirEntryType.ValueType
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        type: global___DirEntryType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "type", b"type"]) -> None: ...

global___DirEntry = DirEntry

@typing_extensions.final
class ReadDirectoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    ENTRIES_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DirEntry]: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
        entries: collections.abc.Iterable[global___DirEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries", "path", b"path", "uri", b"uri"]) -> None: ...

global___ReadDirectoryResponse = ReadDirectoryResponse

@typing_extensions.final
class MakeDirectoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["path", b"path", "uri", b"uri"]) -> None: ...

global___MakeDirectoryRequest = MakeDirectoryRequest

@typing_extensions.final
class MakeDirectoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["path", b"path", "uri", b"uri"]) -> None: ...

global___MakeDirectoryResponse = MakeDirectoryResponse

@typing_extensions.final
class RemoveFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["path", b"path", "uri", b"uri"]) -> None: ...

global___RemoveFileRequest = RemoveFileRequest

@typing_extensions.final
class RemoveFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["path", b"path", "uri", b"uri"]) -> None: ...

global___RemoveFileResponse = RemoveFileResponse

@typing_extensions.final
class RenameFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    NEWFILENAME_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    newFilename: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
        newFilename: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["newFilename", b"newFilename", "path", b"path", "uri", b"uri"]) -> None: ...

global___RenameFileRequest = RenameFileRequest

@typing_extensions.final
class RenameFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    NEWFILENAME_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    newFilename: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
        newFilename: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["newFilename", b"newFilename", "path", b"path", "uri", b"uri"]) -> None: ...

global___RenameFileResponse = RenameFileResponse

@typing_extensions.final
class PutFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    data: builtins.bytes
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "path", b"path", "uri", b"uri"]) -> None: ...

global___PutFileRequest = PutFileRequest

@typing_extensions.final
class PutFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    size: builtins.int
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
        size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["path", b"path", "size", b"size", "uri", b"uri"]) -> None: ...

global___PutFileResponse = PutFileResponse

@typing_extensions.final
class GetFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["path", b"path", "uri", b"uri"]) -> None: ...

global___GetFileRequest = GetFileRequest

@typing_extensions.final
class GetFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    size: builtins.int
    data: builtins.bytes
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
        size: builtins.int = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "path", b"path", "size", b"size", "uri", b"uri"]) -> None: ...

global___GetFileResponse = GetFileResponse

@typing_extensions.final
class BootFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["path", b"path", "uri", b"uri"]) -> None: ...

global___BootFileRequest = BootFileRequest

@typing_extensions.final
class BootFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    uri: builtins.str
    path: builtins.str
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["path", b"path", "uri", b"uri"]) -> None: ...

global___BootFileResponse = BootFileResponse

@typing_extensions.final
class FieldsRequest(google.protobuf.message.Message):
    """////////////////////////////////////////////////////////////////////////////////////////////////
    info messages
    ////////////////////////////////////////////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___Field.ValueType]: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        fields: collections.abc.Iterable[global___Field.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["fields", b"fields", "uri", b"uri"]) -> None: ...

global___FieldsRequest = FieldsRequest

@typing_extensions.final
class FieldsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___Field.ValueType]: ...
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        fields: collections.abc.Iterable[global___Field.ValueType] | None = ...,
        values: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["fields", b"fields", "uri", b"uri", "values", b"values"]) -> None: ...

global___FieldsResponse = FieldsResponse

@typing_extensions.final
class NWACommandRequest(google.protobuf.message.Message):
    """////////////////////////////////////////////////////////////////////////////////////////////////
    NWA messages (emu-nwaccess protocol pass through)
    ////////////////////////////////////////////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URI_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    BINARYARG_FIELD_NUMBER: builtins.int
    uri: builtins.str
    command: builtins.str
    """emu-nwaccess command name:"""
    args: builtins.str
    """command arguments:"""
    binaryArg: builtins.bytes
    """an optional binary argument:"""
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        command: builtins.str = ...,
        args: builtins.str = ...,
        binaryArg: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_binaryArg", b"_binaryArg", "binaryArg", b"binaryArg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_binaryArg", b"_binaryArg", "args", b"args", "binaryArg", b"binaryArg", "command", b"command", "uri", b"uri"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_binaryArg", b"_binaryArg"]) -> typing_extensions.Literal["binaryArg"] | None: ...

global___NWACommandRequest = NWACommandRequest

@typing_extensions.final
class NWACommandResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class NWAASCIIItem(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class ItemEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            value: builtins.str
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        ITEM_FIELD_NUMBER: builtins.int
        @property
        def item(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
        def __init__(
            self,
            *,
            item: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["item", b"item"]) -> None: ...

    URI_FIELD_NUMBER: builtins.int
    ASCIIREPLY_FIELD_NUMBER: builtins.int
    BINARYREPLAY_FIELD_NUMBER: builtins.int
    uri: builtins.str
    @property
    def asciiReply(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NWACommandResponse.NWAASCIIItem]: ...
    binaryReplay: builtins.bytes
    def __init__(
        self,
        *,
        uri: builtins.str = ...,
        asciiReply: collections.abc.Iterable[global___NWACommandResponse.NWAASCIIItem] | None = ...,
        binaryReplay: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_binaryReplay", b"_binaryReplay", "binaryReplay", b"binaryReplay"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_binaryReplay", b"_binaryReplay", "asciiReply", b"asciiReply", "binaryReplay", b"binaryReplay", "uri", b"uri"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_binaryReplay", b"_binaryReplay"]) -> typing_extensions.Literal["binaryReplay"] | None: ...

global___NWACommandResponse = NWACommandResponse
